### ISSUE TITLE
怎样在widgets上添加照片？

### ISSUE THREAD

**Issue by kiwenlau** [pengloo53/light-ch#1]
你好！

我在themes/light/layout/_widget目录下添加了照片“kiwenlau.jpg”以及“photo.ejs”文件，以下为“photo.ejs”文件代码：

```html
<div class="widget tag">
<h3 class="title">KiwenLau</h3>
<ul class="entry">
<li><body><img src="kiwenlau.jpg" style="width:150px; height:150px;"></body></li>
</ul>
```

然后修改了light主题的_config.yml文件，增加photo widgets：
```
widgets:
- photo
- link
- tag
- recent_posts
```

但是部署后的无法显示
![hexo_widgets_image](https://cloud.githubusercontent.com/assets/10240841/8024416/9138d464-0d6d-11e5-8163-07e8c8ef8c34.jpg)

点击图片显示““The requested content cannot be loaded. Please try again later.””

你可以查看我的站点：http://kiwenlau.com/

谢谢！

**Comment by pengloo53** [comment]
请把照片放到source文件夹下，链接地址改成"/kiwenlau.jpg"

**Comment by kiwenlau** [comment]
谢谢！已经解决啦
